apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consul-kv-proxy
  namespace: consul
  labels:
    openshift.io/cluster-monitoring: "true"
spec:
  namespaceSelector:
    matchNames:
      - consul
  selector:
    matchLabels:
      app: consul-kv-proxy
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
